/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'AJ' at '10/30/16 6:24 PM' with Gradle 2.14.1
 *
 * @author AJ, @date 10/30/16 6:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
